### ISSUE TITLE
No updated versions

### ISSUE THREAD

**Issue by andreimarinescu** [bconnorwhite/all-package-names#3]
Hello, just writing to inquire on whether the automatic update process of the library will be restarted at some point or whether we should consider this as deprecated (noticed that the publish job has been failing for the past month).

I do realise we can update the list in code, was just looking to see what the current status of the lib might be.

Thanks!

**Comment by bconnorwhite** [comment]
Thanks for the heads up @andreimarinescu, the action should be unstuck now with a new version released.
