### ISSUE TITLE
needs new preload

### ISSUE THREAD

**Issue by earonesty** [bconnorwhite/all-package-names#4]
probably need to sync more often.   should have sync/release monthly or something?

**Comment by bconnorwhite** [comment]
Looks like its finally large enough to need LFS:

https://github.com/bconnorwhite/all-package-names/actions/runs/4580109500/jobs/8088505734

**Comment by earonesty** [comment]
> Looks like its finally large enough to need LFS:
> 
> [bconnorwhite/all-package-names/actions/runs/4580109500/jobs/8088505734](https://github.com/bconnorwhite/all-package-names/actions/runs/4580109500/jobs/8088505734)

yep.   imo, should probably be gzipped too

**Comment by bconnorwhite** [comment]
I have it syncing the last 3 mos right now and then I'll try to push a fix, might take a while to sync

**Comment by earonesty** [comment]
if you're open to a patch that zips it (code looks for either all.json.zip or all.json and just does the right thing either way), i'll submit a pr.

**Comment by bconnorwhite** [comment]
Didn't see this until I already had a solution, just gzipping it to all.json.gz instead

Probably better that way though, this repo is using an old toolkit that I haven't updated and is annoying to work with. I'll try to have it pushed up later tonight

**Comment by earonesty** [comment]
using `node-gzip` for that?

**Comment by bconnorwhite** [comment]
Finally got the sync to finish, updated and pushed v2.0.662

Just uses node:zlib

https://github.com/bconnorwhite/all-package-names/commit/2f8d47151cfdf95f663ac4b0c8417415a1d24b93
